### ISSUE TITLE
move_servers.sh deleted bedrock server and didn't move it when backup_dir already contained bedrock directory

### ISSUE THREAD

**Issue by mrrogers75** [TapeWerm/MCscripts#40] opened 2021-04-07 23:36 UTC
All setup deleted, I do have world backups....
Error was:
mkdir: cannot create directory ‘/opt/MC/backup_dir/bedrock’: File exists

**Comment by TapeWerm** [comment] 2021-04-08 12:51
The server dir should be in `/tmp/move_servers` or `/tmp/MoveServers`. I think I know why move_servers fails. It was meant for old setups that didn't have a ~mc/bedrock. But if there are bedrock servers both in ~mc and ~mc/bedrock, it will fail. I will make it so it doesn't fail if ~mc/bedrock already exists.

**Comment by TapeWerm** [comment] 2021-04-08 13:01
2beb95a fixes what I suspect is the cause of this. I don't want to close this issue until I confirm this was it though.

**Comment by TapeWerm** [comment] 2021-04-08 13:12
Heh, it fails on the first run if backup_dir resolves to ~mc. I should have tested for that when I made move_servers...
Edit: Eh, on second look it should succeed first run as it only makes a 2nd time if the symlink resolves elsewhere.

**Comment by TapeWerm** [comment] 2021-04-15 16:43
Just checking on this issue, does the update to move_servers fix this? `mkdir -p` will not fail if a directory already exists.

**Comment by TapeWerm** [comment] 2021-05-11 03:53
I'm closing this because it's been a while and I believe I fixed the issue. Feel free to reply to this or make another issue if it happens again.

**Closed as completed by TapeWerm** 2021-05-11 03:53 UTC
